### ISSUE TITLE
Const over Let

### ISSUE THREAD

**Issue by kepop1** [ttudorandrei/code_quiz#3]
https://github.com/ttudorandrei/code_quiz/blob/5d012215f907e40613d543d2d5a3adb47a4dd5a9/assets/js/script.js#L145
https://github.com/ttudorandrei/code_quiz/blob/5d012215f907e40613d543d2d5a3adb47a4dd5a9/assets/js/script.js#L151

These can be const instead of let as they're not redefined.

**Comment by ttudorandrei** [comment]
changed let to var in script.js, lines 145 & 151
